go.exe get -t -v github.com/go-sql-driver/mysql/...
go.exe get -t -v github.com/gogo/protobuf/proto/...
go.exe get -t -v github.com/opentracing/opentracing-go/...
go.exe get -t -v github.com/golang/protobuf/proto/...
go.exe get -t -v github.com/opentracing/opentracing-go/...
go.exe get -t -v github.com/streadway/amqp/...
go.exe get -t -v github.com/influxdata/influxdb/client/v2/...

pause