#!/bin/sh
go get -t -v github.com/go-sql-driver/mysql/...
go get -t -v github.com/gogo/protobuf/proto/...
go get -t -v github.com/opentracing/opentracing-go/...
go get -t -v github.com/golang/protobuf/proto/...
go get -t -v github.com/opentracing/opentracing-go/...
go get -t -v github.com/streadway/amqp/...
go get -t -v github.com/influxdata/influxdb/client/v2/...
go get -t -v github.com/surgemq/message/...

