// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

/*
Package user is a generated protocol buffer package.

It is generated from these files:
	user.proto

It has these top-level messages:
	UserTokenData
	UserData
	UserLoginRequest
	UserLoginResponse
	UserRegisterRequest
	UserRegisterResponse
	UserGetVerifyCodeRequest
	UserGetVerifyCodeResponse
	UserGetSelfInfoRequest
	UserGetSelfInfoResponse
*/
package user

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type UserTokenData struct {
	Token        string `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
	RefreshToken string `protobuf:"bytes,2,opt,name=refreshToken" json:"refreshToken,omitempty"`
	ExpireAt     int64  `protobuf:"varint,3,opt,name=expireAt" json:"expireAt,omitempty"`
}

func (m *UserTokenData) Reset()                    { *m = UserTokenData{} }
func (m *UserTokenData) String() string            { return proto.CompactTextString(m) }
func (*UserTokenData) ProtoMessage()               {}
func (*UserTokenData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *UserTokenData) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *UserTokenData) GetRefreshToken() string {
	if m != nil {
		return m.RefreshToken
	}
	return ""
}

func (m *UserTokenData) GetExpireAt() int64 {
	if m != nil {
		return m.ExpireAt
	}
	return 0
}

type UserData struct {
	UserName string `protobuf:"bytes,1,opt,name=UserName" json:"UserName,omitempty"`
	UserID   string `protobuf:"bytes,2,opt,name=UserID" json:"UserID,omitempty"`
}

func (m *UserData) Reset()                    { *m = UserData{} }
func (m *UserData) String() string            { return proto.CompactTextString(m) }
func (*UserData) ProtoMessage()               {}
func (*UserData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *UserData) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *UserData) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

type UserLoginRequest struct {
	Username string `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
}

func (m *UserLoginRequest) Reset()                    { *m = UserLoginRequest{} }
func (m *UserLoginRequest) String() string            { return proto.CompactTextString(m) }
func (*UserLoginRequest) ProtoMessage()               {}
func (*UserLoginRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *UserLoginRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *UserLoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type UserLoginResponse struct {
	UserTokenData *UserTokenData `protobuf:"bytes,1,opt,name=user_token_data,json=userTokenData" json:"user_token_data,omitempty"`
}

func (m *UserLoginResponse) Reset()                    { *m = UserLoginResponse{} }
func (m *UserLoginResponse) String() string            { return proto.CompactTextString(m) }
func (*UserLoginResponse) ProtoMessage()               {}
func (*UserLoginResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *UserLoginResponse) GetUserTokenData() *UserTokenData {
	if m != nil {
		return m.UserTokenData
	}
	return nil
}

type UserRegisterRequest struct {
	Username   string `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
	Password   string `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
	VerifyCode string `protobuf:"bytes,3,opt,name=verifyCode" json:"verifyCode,omitempty"`
	OpenId     string `protobuf:"bytes,4,opt,name=openId" json:"openId,omitempty"`
}

func (m *UserRegisterRequest) Reset()                    { *m = UserRegisterRequest{} }
func (m *UserRegisterRequest) String() string            { return proto.CompactTextString(m) }
func (*UserRegisterRequest) ProtoMessage()               {}
func (*UserRegisterRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *UserRegisterRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *UserRegisterRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *UserRegisterRequest) GetVerifyCode() string {
	if m != nil {
		return m.VerifyCode
	}
	return ""
}

func (m *UserRegisterRequest) GetOpenId() string {
	if m != nil {
		return m.OpenId
	}
	return ""
}

type UserRegisterResponse struct {
	Result string `protobuf:"bytes,1,opt,name=result" json:"result,omitempty"`
}

func (m *UserRegisterResponse) Reset()                    { *m = UserRegisterResponse{} }
func (m *UserRegisterResponse) String() string            { return proto.CompactTextString(m) }
func (*UserRegisterResponse) ProtoMessage()               {}
func (*UserRegisterResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *UserRegisterResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

type UserGetVerifyCodeRequest struct {
	PhoneNumber string `protobuf:"bytes,1,opt,name=phoneNumber" json:"phoneNumber,omitempty"`
}

func (m *UserGetVerifyCodeRequest) Reset()                    { *m = UserGetVerifyCodeRequest{} }
func (m *UserGetVerifyCodeRequest) String() string            { return proto.CompactTextString(m) }
func (*UserGetVerifyCodeRequest) ProtoMessage()               {}
func (*UserGetVerifyCodeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *UserGetVerifyCodeRequest) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

type UserGetVerifyCodeResponse struct {
}

func (m *UserGetVerifyCodeResponse) Reset()                    { *m = UserGetVerifyCodeResponse{} }
func (m *UserGetVerifyCodeResponse) String() string            { return proto.CompactTextString(m) }
func (*UserGetVerifyCodeResponse) ProtoMessage()               {}
func (*UserGetVerifyCodeResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

type UserGetSelfInfoRequest struct {
}

func (m *UserGetSelfInfoRequest) Reset()                    { *m = UserGetSelfInfoRequest{} }
func (m *UserGetSelfInfoRequest) String() string            { return proto.CompactTextString(m) }
func (*UserGetSelfInfoRequest) ProtoMessage()               {}
func (*UserGetSelfInfoRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

type UserGetSelfInfoResponse struct {
	UserData *UserData `protobuf:"bytes,1,opt,name=userData" json:"userData,omitempty"`
}

func (m *UserGetSelfInfoResponse) Reset()                    { *m = UserGetSelfInfoResponse{} }
func (m *UserGetSelfInfoResponse) String() string            { return proto.CompactTextString(m) }
func (*UserGetSelfInfoResponse) ProtoMessage()               {}
func (*UserGetSelfInfoResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *UserGetSelfInfoResponse) GetUserData() *UserData {
	if m != nil {
		return m.UserData
	}
	return nil
}

func init() {
	proto.RegisterType((*UserTokenData)(nil), "Dolphin.Protocol.UserTokenData")
	proto.RegisterType((*UserData)(nil), "Dolphin.Protocol.UserData")
	proto.RegisterType((*UserLoginRequest)(nil), "Dolphin.Protocol.UserLoginRequest")
	proto.RegisterType((*UserLoginResponse)(nil), "Dolphin.Protocol.UserLoginResponse")
	proto.RegisterType((*UserRegisterRequest)(nil), "Dolphin.Protocol.UserRegisterRequest")
	proto.RegisterType((*UserRegisterResponse)(nil), "Dolphin.Protocol.UserRegisterResponse")
	proto.RegisterType((*UserGetVerifyCodeRequest)(nil), "Dolphin.Protocol.UserGetVerifyCodeRequest")
	proto.RegisterType((*UserGetVerifyCodeResponse)(nil), "Dolphin.Protocol.UserGetVerifyCodeResponse")
	proto.RegisterType((*UserGetSelfInfoRequest)(nil), "Dolphin.Protocol.UserGetSelfInfoRequest")
	proto.RegisterType((*UserGetSelfInfoResponse)(nil), "Dolphin.Protocol.UserGetSelfInfoResponse")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 392 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x92, 0xdf, 0x4b, 0xe3, 0x40,
	0x10, 0xc7, 0xc9, 0xf5, 0xae, 0xb4, 0xd3, 0xeb, 0x5d, 0x2f, 0x57, 0x6a, 0xac, 0xa0, 0x65, 0x9f,
	0xfa, 0x94, 0x82, 0x82, 0x4f, 0x22, 0xa8, 0x81, 0x52, 0x91, 0xa2, 0xf1, 0xc7, 0x83, 0x08, 0x25,
	0x35, 0x93, 0x36, 0x98, 0xee, 0xc6, 0xdd, 0x8d, 0x3f, 0xfe, 0x00, 0xff, 0x6f, 0xd9, 0xcd, 0x36,
	0xa6, 0xda, 0x37, 0x9f, 0xb2, 0x9f, 0x99, 0xd9, 0xef, 0xcc, 0x7e, 0x27, 0x00, 0x99, 0x40, 0xee,
	0xa6, 0x9c, 0x49, 0x66, 0xb7, 0x3c, 0x96, 0xa4, 0xf3, 0x98, 0xba, 0xe7, 0x0a, 0xef, 0x59, 0x42,
	0x10, 0x9a, 0xd7, 0x02, 0xf9, 0x15, 0x7b, 0x40, 0xea, 0x05, 0x32, 0xb0, 0xdb, 0xf0, 0x4b, 0x2a,
	0x70, 0xac, 0x9e, 0xd5, 0xaf, 0xfb, 0x39, 0xd8, 0x04, 0x7e, 0x73, 0x8c, 0x38, 0x8a, 0xb9, 0xae,
	0x74, 0x7e, 0xe8, 0xe4, 0x4a, 0xcc, 0xee, 0x42, 0x0d, 0x5f, 0xd2, 0x98, 0xe3, 0x91, 0x74, 0x2a,
	0x3d, 0xab, 0x5f, 0xf1, 0x0b, 0x26, 0x87, 0x50, 0x53, 0x6d, 0x74, 0x87, 0x6e, 0x7e, 0x1e, 0x07,
	0x0b, 0x34, 0x4d, 0x0a, 0xb6, 0x3b, 0x50, 0x55, 0xe7, 0x91, 0x67, 0x3a, 0x18, 0x22, 0xa7, 0xd0,
	0x52, 0xa7, 0x33, 0x36, 0x8b, 0xa9, 0x8f, 0x8f, 0x19, 0x0a, 0xa9, 0x74, 0xd4, 0xd3, 0x68, 0x49,
	0x67, 0xc9, 0x2a, 0x97, 0x06, 0x42, 0x3c, 0x33, 0x1e, 0x1a, 0xa5, 0x82, 0xc9, 0x1d, 0xfc, 0x2b,
	0x69, 0x89, 0x94, 0x51, 0x81, 0xf6, 0x10, 0xfe, 0xaa, 0xcb, 0x13, 0xfd, 0xdc, 0x49, 0x18, 0xc8,
	0x40, 0x6b, 0x36, 0x76, 0x77, 0xdc, 0xcf, 0x9e, 0xb9, 0x2b, 0x86, 0xf9, 0xcd, 0xac, 0x8c, 0xe4,
	0xcd, 0x82, 0xff, 0xaa, 0xc0, 0xc7, 0x59, 0x2c, 0xa4, 0xfa, 0x7e, 0x6b, 0x5a, 0x7b, 0x1b, 0xe0,
	0x09, 0x79, 0x1c, 0xbd, 0x9e, 0xb0, 0x10, 0xb5, 0xaf, 0x75, 0xbf, 0x14, 0x51, 0x8e, 0xb1, 0x14,
	0xe9, 0x28, 0x74, 0x7e, 0xe6, 0x8e, 0xe5, 0x44, 0x5c, 0x68, 0xaf, 0x8e, 0x61, 0x1e, 0xda, 0x81,
	0x2a, 0x47, 0x91, 0x25, 0xd2, 0x4c, 0x61, 0x88, 0x1c, 0x80, 0xa3, 0xea, 0x87, 0x28, 0x6f, 0x0a,
	0xf1, 0xe5, 0xec, 0x3d, 0x68, 0xa4, 0x73, 0x46, 0x71, 0x9c, 0x2d, 0xa6, 0xc8, 0xcd, 0xc5, 0x72,
	0x88, 0x6c, 0xc1, 0xe6, 0x9a, 0xdb, 0x79, 0x4b, 0xe2, 0x40, 0xc7, 0x24, 0x2f, 0x31, 0x89, 0x46,
	0x34, 0x62, 0x46, 0x98, 0x5c, 0xc0, 0xc6, 0x97, 0x8c, 0x99, 0x73, 0x3f, 0xf7, 0xcb, 0xfb, 0xd8,
	0x44, 0x77, 0xfd, 0x26, 0xf4, 0x12, 0x8a, 0xda, 0xe3, 0xd6, 0xed, 0x1f, 0xd7, 0x1d, 0x2c, 0x58,
	0x98, 0x25, 0x38, 0x50, 0xd1, 0x69, 0x55, 0xff, 0xfb, 0x7b, 0xef, 0x01, 0x00, 0x00, 0xff, 0xff,
	0xae, 0x5e, 0x45, 0x6b, 0x09, 0x03, 0x00, 0x00,
}
