// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

/*
Package user is a generated protocol buffer package.

It is generated from these files:
	user.proto

It has these top-level messages:
	BaseUser
	LoginForm
	RegisterForm
*/
package user

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// DB model
type BaseUser struct {
	// @inject_tag: xorm:"unique index notnull"
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty" xorm:"unique index notnull"`
	// @inject_tag: xorm:"unique index"
	Phone string `protobuf:"bytes,2,opt,name=phone" json:"phone,omitempty" xorm:"unique index"`
	// @inject_tag: json:"-"
	Password string `protobuf:"bytes,3,opt,name=password" json:"password,omitempty" json:"-"`
	// @inject_tag: xorm:"unique index notnull"
	UserID string `protobuf:"bytes,4,opt,name=userID" json:"userID,omitempty" xorm:"unique index notnull"`
	// @inject_tag:  json:"-"
	Id int64 `protobuf:"varint,5,opt,name=id" json:"id,omitempty" json:"-"`
	// @inject_tag:  json:"-"
	CreatTime int64 `protobuf:"varint,6,opt,name=creatTime" json:"creatTime,omitempty" json:"-"`
}

func (m *BaseUser) Reset()                    { *m = BaseUser{} }
func (m *BaseUser) String() string            { return proto.CompactTextString(m) }
func (*BaseUser) ProtoMessage()               {}
func (*BaseUser) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *BaseUser) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *BaseUser) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *BaseUser) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *BaseUser) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *BaseUser) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *BaseUser) GetCreatTime() int64 {
	if m != nil {
		return m.CreatTime
	}
	return 0
}

type LoginForm struct {
	Name     string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
}

func (m *LoginForm) Reset()                    { *m = LoginForm{} }
func (m *LoginForm) String() string            { return proto.CompactTextString(m) }
func (*LoginForm) ProtoMessage()               {}
func (*LoginForm) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *LoginForm) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *LoginForm) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type RegisterForm struct {
	Name       string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Password   string `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
	VerifyCode string `protobuf:"bytes,3,opt,name=verifyCode" json:"verifyCode,omitempty"`
}

func (m *RegisterForm) Reset()                    { *m = RegisterForm{} }
func (m *RegisterForm) String() string            { return proto.CompactTextString(m) }
func (*RegisterForm) ProtoMessage()               {}
func (*RegisterForm) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *RegisterForm) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RegisterForm) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *RegisterForm) GetVerifyCode() string {
	if m != nil {
		return m.VerifyCode
	}
	return ""
}

func init() {
	proto.RegisterType((*BaseUser)(nil), "user.BaseUser")
	proto.RegisterType((*LoginForm)(nil), "user.LoginForm")
	proto.RegisterType((*RegisterForm)(nil), "user.RegisterForm")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 210 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0x2d, 0x4e, 0x2d,
	0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x01, 0xb1, 0x95, 0xa6, 0x31, 0x72, 0x71, 0x38,
	0x25, 0x16, 0xa7, 0x86, 0x16, 0xa7, 0x16, 0x09, 0x09, 0x71, 0xb1, 0xe4, 0x25, 0xe6, 0xa6, 0x4a,
	0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0x81, 0xd9, 0x42, 0x22, 0x5c, 0xac, 0x05, 0x19, 0xf9, 0x79,
	0xa9, 0x12, 0x4c, 0x60, 0x41, 0x08, 0x47, 0x48, 0x8a, 0x8b, 0xa3, 0x20, 0xb1, 0xb8, 0xb8, 0x3c,
	0xbf, 0x28, 0x45, 0x82, 0x19, 0x2c, 0x01, 0xe7, 0x0b, 0x89, 0x71, 0xb1, 0x81, 0x8c, 0xf6, 0x74,
	0x91, 0x60, 0x01, 0xcb, 0x40, 0x79, 0x42, 0x7c, 0x5c, 0x4c, 0x99, 0x29, 0x12, 0xac, 0x0a, 0x8c,
	0x1a, 0xcc, 0x41, 0x4c, 0x99, 0x29, 0x42, 0x32, 0x5c, 0x9c, 0xc9, 0x45, 0xa9, 0x89, 0x25, 0x21,
	0x99, 0xb9, 0xa9, 0x12, 0x6c, 0x60, 0x61, 0x84, 0x80, 0x92, 0x35, 0x17, 0xa7, 0x4f, 0x7e, 0x7a,
	0x66, 0x9e, 0x5b, 0x7e, 0x51, 0x2e, 0x56, 0x87, 0x21, 0x3b, 0x81, 0x09, 0xd5, 0x09, 0x4a, 0x71,
	0x5c, 0x3c, 0x41, 0xa9, 0xe9, 0x99, 0xc5, 0x25, 0xa9, 0x45, 0xe4, 0xe8, 0x17, 0x92, 0xe3, 0xe2,
	0x2a, 0x4b, 0x2d, 0xca, 0x4c, 0xab, 0x74, 0xce, 0x4f, 0x49, 0x85, 0x7a, 0x10, 0x49, 0x24, 0x89,
	0x0d, 0x1c, 0x84, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0xd6, 0x36, 0xd3, 0xe9, 0x50, 0x01,
	0x00, 0x00,
}
